#pragma once
#include <set>
#include <vector>

#include "BuildCache.hpp"
#include "BuildConfiguration.hpp"
#include "FilePath.hpp"
#include "Project.hpp"
#include "base.hpp"
#include "code/SourceProcessor.hpp"
#include "code/SourceTools.hpp"
#include "misc/hash128.hpp"

namespace build_tools
{
  enum _ExecuteFlags : uint8_t {
    eExcFlag_Printout = 0x01,
    eExcFlag_PrintoutProgress = 0x02,
  };

  typedef std::underlying_type_t<_ExecuteFlags> ExecuteFlags;

  struct BuildCommandInfo
  {
    ExecuteFlags flags = eExcFlag_Printout;
    std::ostream *out;
    StaticString<128> name;
    bool critical = false;
    std::vector<string> args;
    FilePath in_path;
    FilePath out_path;
  };

  extern void WriteAutoGeneratedHeader(std::ostream &stream);

  extern vector<FilePath> GetAllFilesInDirectory(const FilePath &path,
                                                 bool recursive = true);

  extern FilePath DefaultProjectFilePath();

  extern string EscapeQuotes(const StrBlob &str);
  static inline string EscapeQuotes(const string &str) {
    return EscapeQuotes(StrBlob(str.data(), str.size()));
  }

  extern SourceFileType GetSourceType(const StrBlob &path);
  extern bool IsCompilableSourceFile(const StrBlob &path);

  extern void DeleteBuildCache(const Project &project);
  extern void DeleteBuildDir(const Project &project);
  extern void SetupHashes(BuildCache &cache,
                          const Project &proj,
                          const BuildConfiguration *config);

  extern hash_t GetFileHash(const char *path);

  extern void DeleteUnusedObjFiles(const std::set<FilePath> &object_files,
                                   const std::set<FilePath> &used_files);

  extern std::vector<int> Execute(const Blob<const BuildCommandInfo> &params);
  extern std::vector<int> Execute_Multithreaded(
      const Blob<const BuildCommandInfo> &params,
      uint32_t batches);

  extern errno_t _Execute_Inner(const Blob<const std::string> &args,
                                const Blob<const BuildCommandInfo> &params,
                                Blob<int> results);

  extern errno_t _ExecuteParallel_Inner(
      const Blob<const std::string> &args,
      const Blob<const BuildCommandInfo> &params,
      Blob<int> results,
      uint32_t batches);

  extern SourceFileType GetDominantSourceType(
      Blob<const SourceFileType> file_types);

  extern bool IsAllowedForClangdFlags(const std::string &str);

  extern void TryCreateClangdCompileFlagsFile(const BuildConfiguration &config,
                                              const FilePath &build_folder);

  extern void WriteClangdCompileCommandsFile(const std::string *args,
                                             const std::string *names,
                                             size_t count,
                                             const FilePath &build_folder);

  extern SourceFileType DefaultSourceFileTypeForFilePath(
      const FilePath::char_type *path);
  extern SourceFileType DefaultSourceFileTypeForFilePath(const FilePath &path);

  extern SourceFileType DefaultSourceFileTypeForExtension(
      FilePath::string_blob extension);
  extern SourceFileType DefaultSourceFileTypeForExtension(
      const FilePath::string_type &extension);

  extern const char *GetSourceFileTypeName(SourceFileType type);

  // for 'c++' and 'c' and stuff (not for finding file extension's type, see
  // DefaultSourceFileTypeForExtension())
  extern SourceFileType GetFileTypeFromTypeName(
      FilePath::string_blob file_type_name);

  static inline SourceFileType GetFileTypeFromTypeName(
      const FilePath::string_type &str) {
    return GetFileTypeFromTypeName(
        FilePath::string_blob{ str.c_str(), str.length() });
  }

  extern void DumpDependencyMap(const SourceProcessor::dependency_info_map &map,
                                const FilePath &output_path);

  template <typename PRED>
  static inline string JoinArguments(const std::string *args,
                                     size_t count,
                                     PRED &&pred) {
    std::ostringstream oss;

    for (size_t i = 0; i < count; i++)
    {
      if (!pred(args[i]))
      {
        continue;
      }

      bool need_enclosure =
          string_tools::all_of(args[i].c_str(),
                               [](char value) { return !isgraph(value); });

      if (need_enclosure)
      {
        oss << '"' << args[i] << '"';
      }
      else
      {
        oss << args[i];
      }

      oss << ' ';
    }

    return oss.str();
  }

  static inline string JoinArguments(const std::string *args, size_t count) {
    return JoinArguments(args, count, [](const std::string &s) {
      (void)s;
      return true;
    });
  }
}
