#include "BuildTools.hpp"

#include <cstdio>
#include <fstream>
#include <vector>

#include "FilePath.hpp"
#include "HashTools.hpp"
#include "Settings.hpp"
#include "base.hpp"
#include "utility/Process.hpp"
#include "utility/ThreadBatcher.hpp"

using namespace build_tools;

static bool DoesSourceTypeDominate(SourceFileType type, SourceFileType target);
static void GenerateJoinArgs(const Blob<const BuildCommandInfo> &params,
                             std::string *results);

void build_tools::WriteAutoGeneratedHeader(std::ostream &stream) {
  std::time_t now =
      std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());

  stream << "# This file is temporay and was generated on "
         << std::put_time(std::localtime(&now), "%Y-%m-%d %X") << '\n'
         << "# written by bgnu " << Settings::GetVersion() << '\n';
}

vector<FilePath> build_tools::GetAllFilesInDirectory(const FilePath &path,
                                                     bool recursive) {
  vector<FilePath> entries{};
  vector<FilePath::iterator> iterators{};

  iterators.push_back(path.create_iterator());

  while (!iterators.empty())
  {
    const auto current_iter = iterators.back();
    iterators.pop_back();

    for (const auto &path : current_iter)
    {
      if (path.is_directory())
      {
        if (recursive)
        {
          iterators.emplace_back(path);
        }
        continue;
      }

      if (path.is_regular_file())
      {
        entries.push_back(path);
        continue;
      }

      // skips other non-regular files
    }
  }

  return entries;
}

FilePath build_tools::DefaultProjectFilePath() {
  return FilePath::get_working_directory().join_path(".bgnu");
}

StandardType build_tools::FitStandardToFileType(StandardType type,
                                                SourceFileType file_type) {
  typedef StandardType E;
  typedef SourceFileType S;

  const bool use_draft_c2x = Settings::Get("use_draft_c2x", false).get_bool();

  if (file_type == SourceFileType::None)
  {
    return type;
  }

  switch (type)
  {
  case E::C11: {
    if (file_type == S::CPP)
    {
      return E::Cpp11;
    }

    return E::C11;
  }

  case E::C14: {
    if (file_type == S::CPP)
    {
      return E::Cpp14;
    }

    return E::C14;
  }

  case E::C17: {
    if (file_type == S::CPP)
    {
      return E::Cpp17;
    }

    return E::C17;
  }

  case E::C2x: {
    if (file_type == S::CPP)
    {
      return E::Cpp20;
    }

    return use_draft_c2x ? E::C2x : E::C23;
  }

  case E::C23: {
    if (file_type == S::CPP)
    {
      return E::Cpp23;
    }

    return E::C23;
  }

    // c++

  case E::Cpp11: {
    if (file_type == S::C)
    {
      return E::C11;
    }

    return E::Cpp11;
  }

  case E::Cpp14: {
    if (file_type == S::C)
    {
      return E::C14;
    }

    return E::Cpp14;
  }

  case E::Cpp17: {
    if (file_type == S::C)
    {
      return E::C17;
    }

    return E::Cpp17;
  }

  case E::Cpp20: {
    if (file_type == S::C)
    {
      return use_draft_c2x ? E::C2x : E::C23;
    }

    return E::Cpp20;
  }

  case E::Cpp23: {
    if (file_type == S::C)
    {
      return E::C23;
    }

    return E::Cpp23;
  }

  default:
    return type;
  }
}

string build_tools::EscapeQuotes(const StrBlob &str) {
  string result = {};
  result.reserve(str.length);

  for (size_t i = 0; i < str.length; i++)
  {
    if (str[i] == '"')
    {
      result.push_back('\\');
    }

    result.push_back(str[i]);
  }

  return result;
}

SourceFileType build_tools::GetSourceType(const StrBlob &path) {
  return SourceTools::get_extension_file_type(FilePath::GetExtension(path));
}

bool build_tools::IsCompilableSourceFile(const StrBlob &path) {
  return SourceTools::is_extension_compilable(FilePath::GetExtension(path));
}

void build_tools::DeleteBuildCache(const Project &project) {
  project.get_output().cache_dir->remove_recursive();
}

void build_tools::DeleteBuildDir(const Project &project) {
  DeleteBuildCache(project);
  project.get_output().dir->remove_recursive();
}

void build_tools::SetupHashes(BuildCache &cache,
                              const Project &proj,
                              const BuildConfiguration *config) {
  cache.build_hash = proj.hash();
  cache.config_hash = config->hash();
}

hash_t build_tools::GetFileHash(const char *path) {
  FILE *fp = fopen(path, "r");

  if (fp == nullptr)
  {
    Logger::error("No File to hash at '%s'", path);
    return 0;
  }

  const auto start = ftello(fp);
  fseek(fp, 0, SEEK_END);
  const auto end = ftell(fp);
  rewind(fp);

  const auto len = end - start;
  char *p = new char[len]{};

  const auto read_len = fread(p, 1, len, fp);

  fclose(fp);

  if (read_len != len)
  {
    Logger::warning(
        "Hashing file '%s' might fail: len=%ld [%ld -> %ld], read_ln=%ld",
        path,
        len,
        start,
        end,
        read_len);
  }

  auto hash = HashTools::hash(StrBlob(p, len), 0);

  delete[] p;

  return hash;
}

void build_tools::DeleteUnusedObjFiles(const std::set<FilePath> &object_files,
                                       const std::set<FilePath> &used_files) {
  for (const auto &obj : object_files)
  {
    if (used_files.contains(obj))
    {
      continue;
    }

    if (obj.is_file())
    {
      obj.remove();
    }
  }
}

#define EXECUTE_CHECK_ERR()                                                   \
  if (error != EOK)                                                           \
  {                                                                           \
    Logger::error(                                                            \
        "failed to execute params in function %s with error=%s, check above " \
        "logs^^",                                                             \
        __FUNCTION__,                                                         \
        GetErrorName(error));                                                 \
  }

std::vector<int> build_tools::Execute(
    const Blob<const BuildCommandInfo> &params) {

  std::vector<std::string> joined_commands{};
  joined_commands.resize(params.size());

  GenerateJoinArgs(params, joined_commands.data());

  vector<int> results{};
  results.resize(params.size());

  const errno_t error =
      _Execute_Inner({ joined_commands.data(), joined_commands.size() },
                     params,
                     { results.data(), results.size() });

  EXECUTE_CHECK_ERR();

  return results;
}

std::vector<int> build_tools::Execute_Multithreaded(
    const Blob<const BuildCommandInfo> &params,
    uint32_t batches) {

  std::vector<std::string> joined_commands{};
  joined_commands.resize(params.size());

  GenerateJoinArgs(params, joined_commands.data());

  vector<int> results{};
  results.resize(params.size());

  const errno_t error =
      _ExecuteParallel_Inner({ joined_commands.data(), joined_commands.size() },
                             params,
                             { results.data(), results.size() },
                             batches);

  EXECUTE_CHECK_ERR();

  return results;
}

errno_t build_tools::_Execute_Inner(const Blob<const std::string> &args,
                                    const Blob<const BuildCommandInfo> &params,
                                    Blob<int> results) {
  for (size_t i = 0; i < args.length; i++)
  {
    const auto &param = params[i];
    Process process{ args[i] };
    process.set_name(param.name.c_str());

    if (HAS_FLAG(param.flags, eExcFlag_Printout))
    {
      Logger::notify("executing '%s'...", param.name.c_str());
    }

    results[i] = process.start(param.out);

    if (HAS_FLAG(param.flags, eExcFlag_Printout))
    {
      Logger::notify("executing '%s' resulted in code %d [%llu / %llu]",
                     param.name.c_str(),
                     results[i],
                     i,
                     args.length);
    }
  }

  return EOK;
}

errno_t build_tools::_ExecuteParallel_Inner(
    const Blob<const std::string> &args,
    const Blob<const BuildCommandInfo> &params,
    Blob<int> results,
    uint32_t batches) {
  std::atomic_size_t progress_index = 0;
  const auto func = [&args, &params, &progress_index](size_t index) {
    const auto &param = params[index];
    Process process{ args[index] };

#ifdef __linux__
    process.add_flags(Process::Flag_InheritEnv);
#endif
    process.set_name(param.name.c_str());

    Logger::verbose("processing parallel: '%s'", args[index].c_str());

    if (HAS_FLAG(param.flags, eExcFlag_Printout))
    {
      Logger::notify("executing '%s'...", param.name.c_str());
    }

    const int result = process.start(param.out);
    progress_index++;

    if (HAS_FLAG(param.flags, eExcFlag_Printout))
    {
      const auto log_func = (result == EOK) ? Logger::notify : Logger::warning;
      log_func("executing '%s' resulted in %s [%d] [%llu / %llu]",
               param.name.c_str(),
               GetErrorName(result),
               result,
               (size_t)progress_index,
               args.length);
    }

    return result;
  };

  const auto exporter = [&results](size_t index, int result) {
    results[index] = result;
  };

  ThreadBatcher batcher = { batches, func, exporter };

  batcher.run(args.length);

  return errno_t();
}

SourceFileType build_tools::GetDominantSourceType(
    Blob<const SourceFileType> file_types) {
  SourceFileType dominate_type = SourceFileType::None;

  for (SourceFileType type : file_types)
  {
    if (DoesSourceTypeDominate(type, dominate_type))
    {
      dominate_type = type;
    }
  }

  return dominate_type;
}

bool build_tools::IsAllowedForClangdFlags(const std::string &str) {
  if (str == "-Wfatal-errors")
  {
    return false;
  }

  if (str.starts_with("-std="))
  {
    return false;
  }

  return true;
}

bool build_tools::IsAllowedForClangdCommands(const std::string &str) {
  if (str == "-Wfatal-errors")
  {
    return false;
  }

  return true;
}

void build_tools::TryCreateClangdCompileFlagsFile(
    const BuildConfiguration &config,
    const FilePath &build_folder) {
  const FilePath compile_flags_file =
      build_folder.join_path("compile_flags.txt");
  if (compile_flags_file.is_file() && !compile_flags_file.is_empty())
  {
    return;
  }

  vector<string> flags{};
  config.build_clangd_contents(flags);

  auto file = compile_flags_file.stream_write(false);
  for (const string &s : flags)
  {
    if (!IsAllowedForClangdFlags(s))
    {
      continue;
    }
    file << s;
    file << '\n';
  }
}

void build_tools::WriteClangdCompileCommandsFile(const std::string *args,
                                                 const std::string *names,
                                                 size_t count,
                                                 const FilePath &build_folder) {

  const FilePath compile_cmds_path =
      build_folder.join_path("compile_commands.json");
  auto file = compile_cmds_path.stream_write(false);

  file << "[";

  for (size_t i = 0; i < count; i++)
  {
    file << "\n\t{\n";

    file << "\t\t";
    file << "\"directory\": " << '"' << EscapeQuotes(build_folder) << '"'
         << "\n,";
    file << "\t\t";
    file << "\"command\": " << '"' << EscapeQuotes(args[i]) << '"' << "\n,";

    file << "\t\t";
    file << "\"file\": " << '"' << EscapeQuotes(names[i]) << '"' << "\n";

    file << "\t},";
  }

  file << "\n]";
}

SourceFileType build_tools::DefaultSourceFileTypeForFilePath(
    const FilePath::char_type *path) {
  const size_t extension_index =
      string_tools::find_last(path, '.', FilePath::MaxPathLength);
  const size_t path_length = string_tools::length(path);

  if (extension_index == npos || extension_index + 1 >= path_length)
  {
    return SourceFileType::None;
  }

  const auto *extension = path + extension_index + 1;

  return DefaultSourceFileTypeForExtension(
      FilePath::string_blob{ extension, path_length - extension_index - 1 });
}

SourceFileType build_tools::DefaultSourceFileTypeForFilePath(
    const FilePath &path) {
  return DefaultSourceFileTypeForFilePath(path.c_str());
}

SourceFileType build_tools::DefaultSourceFileTypeForExtension(
    FilePath::string_blob extension) {
  constexpr const FilePath::char_type *CPPExtensions[] = {
    "cpp", "c++", "cc", "cxx",

    "hpp", "h++", "hh", "hxx",
  };

  constexpr const FilePath::char_type *CExtensions[] = {
    "c",
    "h",
  };

#define CHECK_EXT(type, ext_list)                                       \
  for (size_t i = 0; i < std::size(ext_list); i++)                      \
  {                                                                     \
    if (string_tools::equal_insensitive(extension.data, (ext_list)[i])) \
    {                                                                   \
      return type;                                                      \
    }                                                                   \
  }

  CHECK_EXT(SourceFileType::CPP, CPPExtensions);
  CHECK_EXT(SourceFileType::C, CExtensions);

  return SourceFileType::None;
}

SourceFileType build_tools::DefaultSourceFileTypeForExtension(
    const FilePath::string_type &extension) {
  return DefaultSourceFileTypeForExtension(
      FilePath::string_blob{ extension.c_str(), extension.length() });
}

const char *build_tools::GetSourceFileTypeName(SourceFileType type) {
  switch (type)
  {
  case SourceFileType::C:
    return "C";
  case SourceFileType::CPP:
    return "Cpp";
  default:
    return "unknown";
  }
}

SourceFileType build_tools::GetFileTypeFromTypeName(
    FilePath::string_blob file_type_name) {
  return DefaultSourceFileTypeForExtension(file_type_name);  // yeah...
}

void build_tools::DumpDependencyMap(
    const SourceProcessor::dependency_info_map &map,
    const FilePath &output_dir) {
  const FilePath output_path = output_dir.join_path("dependency.txt");

  std::ofstream stream = output_path.stream_write(false);

  const std::streampos start = stream.tellp();

  WriteAutoGeneratedHeader(stream);
  stream << "# below is the dependency map of the entire project\n";

  // We can do it by converting 'map' to field var and save it
  // sadly, im too lazy rn

  for (const auto &[name, deps] : map)
  {
    stream << name << ":\n[\n";
    for (const auto &dep_name : deps.sub_dependencies)
    {
      stream << "  \"" << dep_name << "\", # "
             << FilePath(dep_name).resolved_copy(name.parent()) << "\n";
    }
    stream << "]\n\n";
  }

  Logger::verbose("dumped the dependency map: size=%lld bytes",
                  stream.tellp() - start);
}

bool DoesSourceTypeDominate(SourceFileType type, SourceFileType target) {
  constexpr std::pair<SourceFileType, SourceFileType> DominationTable[] = {
    { SourceFileType::CPP, SourceFileType::C },
  };

  // a type can not dominate it's own kind
  if (type == target)
  {
    return false;
  }

  // every type dominates the none type
  if (target == SourceFileType::None)
  {
    return true;
  }

  // the none type can't dominate any type
  if (type == SourceFileType::None)
  {
    return false;
  }

  for (const auto &i : DominationTable)
  {
    if (i == decltype(DominationTable[0]){ type, target })
    {
      return true;
    }
  }

  return false;
}

void GenerateJoinArgs(const Blob<const BuildCommandInfo> &params,
                      std::string *results) {

  for (size_t i = 0; i < params.size(); i++)
  {
    std::ostringstream oss;

    for (const string &str : params[i].args)
    {
      oss << str << ' ';
    }

    results[i] = oss.str();
    results[i].pop_back();
  }
}
